version: "3"

services:
  react:
    container_name: react
    build:
      # the context (working directory) is the current directory
      # change this to the directory containing the dockerfile if in a different place
      context: .
      dockerfile: # the dockerfile to be run
        Dockerfile
    expose:
      - 80
    networks:
      - proxy_default

networks:
  proxy_default:
    external: true
